# Azure DevOps pipeline to release a new version and deploy to production.
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docs/*

pr: none

parameters:
  - name: "TARGET_ENV"
    displayName: "Target Environment"
    type: string
    default: "PROD"
    values:
      - "DEV"
      - "UAT"
      - "PROD"

variables:
  vmImageNameDefault: 'ubuntu-latest'
  blob_container_path: 'piattaformaunitaria-legaldocs'

  # Setting env specific settings
  ${{ if eq(parameters.TARGET_ENV, 'DEV') }}:
    environment: 'DEV'
    azure_subscription: '$(DEV_AZURE_SUBSCRIPTION)'
    cdn_endpoint: '$(DEV_CDN_ENDPOINT)'
    cdn_profile: '$(DEV_CDN_PROFILE)'
    cdn_domains: '$(DEV_CDN_DOMAINS)'
    storage_account: '$(DEV_STORAGE_ACCOUNT_NAME)'
    resource_group: '$(DEV_STORAGE_ACCOUNT_RG)'

  ${{ if eq(parameters.TARGET_ENV, 'UAT') }}:
    environment: 'UAT'
    azure_subscription: '$(UAT_AZURE_SUBSCRIPTION)'
    cdn_endpoint: '$(UAT_CDN_ENDPOINT)'
    cdn_profile: '$(UAT_CDN_PROFILE)'
    cdn_domains: '$(UAT_CDN_DOMAINS)'
    storage_account: '$(UAT_STORAGE_ACCOUNT_NAME)'
    resource_group: '$(UAT_STORAGE_ACCOUNT_RG)'

  ${{ if eq(parameters.TARGET_ENV, 'PROD') }}:
    environment: 'PROD'
    azure_subscription: '$(PROD_AZURE_SUBSCRIPTION)'
    cdn_endpoint: '$(PROD_CDN_ENDPOINT)'
    cdn_profile: '$(PROD_CDN_PROFILE)'
    cdn_domains: '$(PROD_CDN_DOMAINS)'
    storage_account: '$(PROD_STORAGE_ACCOUNT_NAME)'
    resource_group: '$(PROD_STORAGE_ACCOUNT_RG)'

pool:
  vmImage: '$(vmImageNameDefault)'

stages:
  # Deploy docs
  - stage: stage_deploy
    displayName: 'Deploy to ${{ variables.environment }} storage'
    jobs:
      - job: job_deploy
        displayName: 'Deploy'
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 1

          - task: AzureCLI@2
            displayName: 'Sync storage'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob sync --container '$web' --account-name $(storage_account) --source 'docs' --destination '$(blob_container_path)/'

          - task: AzureCLI@1
            displayName: 'Purge CDN endpoint'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptLocation: inlineScript
              inlineScript: |
                az afd endpoint purge -g $(resource_group) --endpoint-name $(cdn_endpoint) --profile-name $(cdn_profile) --domains $(cdn_domains) --content-paths "/$(blob_container_path)/*"
